import React from "react";

const Terms = () => {


    return (
        <div style={{ padding: "20px 50px" }}>
            <h1>Overview</h1>
            <p>The following provides an overview of our Terms and Conditions applicable to our
                Platform, encompassing any website, application, or service offered by us. It is
                imperative that you thoroughly read the complete Terms and Conditions, as that
                document, and not this overview, constitutes our legally binding agreement. The
                comprehensive Terms and Conditions details information about your legal rights,
                addressing crucial aspects such as limitations of liability, the resolution of disputes
                through mandatory arbitration rather than a court of law with a judge or jury, and the
                inclusion of a class action waiver. Familiarizing yourself with the complete Terms and
                Conditions is essential for a comprehensive understanding of the terms and conditions
                governing your use of our Platform.
                Last Updated: December 12, 2023</p>

            <h1>1 - Key Definitions</h1>
            <p>Within these Terms and Conditions, the subsequent terms are capitalized, whether in
                singular or plural form. The usage of these terms is meant to signify the following:
            </p>

            <ul>

                <li>SportiveBuddy: SportiveBuddy OÜ (hereinafter SportiveBuddy), with its
                    headquarter located at Akadeemia tee 5, Tallinn, Estonia. SportiveBuddy was
                    established on August 21, 2023 as Private limited company, and is registered
                    under number 16801469 in Tallinn, Estonia</li>
                <li>Content: Information shared by Users on the platform, encompassing, but not
                    restricted to, User Profiles.</li>
                <li>Database: The compilation of data generated by SportiveBuddy, comprising
                    Profiles and additional Content.</li>
                <li>Service: The service that SportiveBuddy offers to the User, as outlined in Article 3.</li>
                <li>User: An individual who has formally established a Profile and engages in the
                    utilization of the Service.</li>
                <li>Terms and Conditions: The regulations outlined in this document</li>
                <li>Log-in Credentials: The combination of the designated username and password
                    assigned to the User constitutes the authentication credentials that grant access
                    to their Profile and facilitate the utilization of the Service.
                    • Intellectual Property Rights: The comprehensive spectrum of intellectual property
                    and associated rights includes, but is not confined to, copyrights, trademark rights,
                    database rights, trade name rights, neighboring rights, as well as entitlements to
                    know-how and initial performances</li>
                <li>Privacy Policy: The privacy statement of SportiveBuddy, which articulates the
                    policies and practices related to the handling of personal information, can be
                    accessed through the provided hyperlink –
                    https://www.sportivebuddy.com/privacy-policy/</li>
                <li>Profile: A depiction provided by a User on the platform, encompassing details such
                    as full name, description, gender, age, country, preferred sport, posts and
                    potentially including a visual representation, like a picture.</li>
                <li>Platform: The overarching platform of SportiveBuddy, inclusive of all underlying
                    systems that support its functionality.
                </li>

            </ul>


            <h1>2 - General:
            </h1>
            <p>2.1 SportiveBuddy retains the ongoing authority to make modifications and/or additions
                to these Terms and Conditions. The most up-to-date iteration of the Terms and
                Conditions is accessible on the Website, Platform or will be brought to your attention
                during the course of using the Service. By persisting in the utilization of the Service
                subsequent to any alterations and/or additions to these Terms and Conditions, you are
                thereby expressing irrevocable acceptance of the amended or supplemented Terms
                and Conditions. In the event that you do not consent to the modified and/or
                supplemented Terms and Conditions, your singular recourse is to discontinue using
                the Service and proceed to remove your Profile.
            </p>

            <p>2.2 While we dedicate considerable efforts to ensure the consistent availability and
                seamless operation of our Platform, it is important to note that absolute certainty in this
                regard cannot be guaranteed. Like any complex system, occasional unforeseen events
                or circumstances may disrupt the anticipated smooth operation. We sincerely
                apologize in advance for any inconvenience that may arise from such situations.
                Please rest assured that we are committed to promptly addressing and resolving any
                issues to enhance the overall reliability and user experience of our Platform.</p>

            <p>2.3 Should you have any inquiries or encounter any misunderstandings pertaining to
                our terms and conditions or the functionality of our platform, we warmly invite you to
                contact us via email (support@sportivebuddy.com). Our dedicated support team is
                here to assist you and address any concerns you may have. We value transparency
                and are committed to providing comprehensive explanations and guidance to ensure
                that your experience on our platform is not only enjoyable but also fully aligned with
                your expectations. Your satisfaction and understanding are of utmost importance to
                us, and we appreciate the opportunity to assist you further.</p>



            <h1>3 - The Service:</h1>


            <p>3.1 The Service extends the capability for users to meticulously craft and publish a
                Profile, discernible solely by other duly registered users. The inherent purpose of this
                Service is to orchestrate the convergence of individuals for the purpose of engaging in
                sports activities through the Platform. The formulation of perceptions regarding the
                attributes and qualities of fellow users is facilitated through the perusal of Profiles,
                thereby serving as a fundamental component of the Service's functionality.</p>



            <p>3.2 The Service encompasses the facilitation of access to a Database housing other
                members actively seeking a sports partner, allowing users to initiate contact for
                organizing sports engagements, sharing perspectives, and establishing personal
                objectives. Additional conditions governing the user's utilization of the Service may be
                stipulated on the Platform. These supplementary conditions pertain, among other
                aspects, to the procedures governing the creation and posting of Profiles.</p>

            <h1>4 - The entitlement to access the Service and its
                corresponding availability.
            </h1>

            <ul>
                <li>4.1 In order to utilize the Service, it is imperative to create a Profile following the
                    outlined procedures on the Platform. It is expressly prohibited to generate a Profile
                    under another individual's identity. As part of the registration process, it is mandatory
                    to furnish Log-in Credentials, serving as the means through which access to the
                    created Profile is facilitated.
                </li>
                <li>4.2 You bear the responsibility for maintaining the confidentiality of your Log-in
                    Credentials. Disclosing your Log-in Credentials to third parties is strictly prohibited. Any
                    use of the Service under your Log-in Credentials is your responsibility, and
                    SportiveBuddy may reasonably assume that you are the authorized user associated
                    with that Log-in Credentials. In the event that you become aware or have reason to
                    suspect that your Log-in Credentials has been accessed by unauthorized individuals,
                    it is imperative to promptly notify SportiveBuddy. This notification does not absolve you
                    of the obligation to take effective measures independently, such as altering your Login Credentials. SportiveBuddy shall not be held liable for any damages arising from
                    unauthorized access to or use of the Website and/or Service by third parties.</li>
                <li>4.3 SportiveBuddy maintains the unequivocal right, without the obligation of prior notice
                    and without assuming any indebtedness or liability towards you, to effectuate (i)
                    procedural and technical modifications and/or improvements to the Service, and (ii) the
                    (temporary or permanent) deactivation, restriction, or removal of the Service or your
                    Profile. This authority is exercised at the sole discretion of SportiveBuddy and is
                    intended to ensure the continued refinement and optimal functioning of the Service.</li>
                <li>4.4 SportiveBuddy expressly disclaims any liability or obligation towards you for any
                    damages, whether direct or consequential, that may arise or result from the
                    (temporary) unavailability or (intermediate) interruption of the Website and/or the Service.
                    This exculpation extends to any adverse consequences, inconveniences, or losses
                    incurred by users during such periods. SportiveBuddy, in exercising due diligence,
                    endeavors to minimize any disruptions, but it is not held accountable for any associated
                    damages that users may experience during instances of unavailability or interruption
                    of the Platform and/or the Service.</li>
                <li>4.5 SportiveBuddy explicitly refrains from offering any guarantees, promises, or
                    assurances regarding the quality, safety, legality, integrity, and accuracy of the
                    Platform and the Service, unless stipulated otherwise within the confines of these
                    Terms and Conditions. The user is hereby notified that any implied warranties or
                    representations are expressly disclaimed, and SportiveBuddy assumes no
                    responsibility for the overall performance, reliability, or suitability of the Website and
                    the Service for individual users' purposes, unless expressly stated otherwise in these
                    Terms and Conditions.</li>
                <li>4.6 The onus for the acquisition and/or effective operation of the requisite infrastructure
                    and robust telecommunication facilities, encompassing, but not limited to, a
                    dependable internet connection, necessary for the utilization of the Service, rests
                    entirely upon you. It is incumbent upon you to ensure the adequacy and functionality
                    of the aforementioned components to enable seamless access to and use of the
                    Service. SportiveBuddy assumes no responsibility for any deficiencies or failures in
                    your personal infrastructure and telecommunications setup that may impede or affect
                    the optimal functioning of the Service.</li>
            </ul>

            <h1>5 - Utilizing the Service
            </h1>

            <p>5.1 SportiveBuddy explicitly disclaims any knowledge of or direct involvement in the
                Content provided by users. It operates solely as a platform for connecting individuals
                in search of sports partners and does not function as a mediation agency. The primary
                objective of the Service is to facilitate the unification of individuals with common
                sporting interests. Notably, SportiveBuddy abstains from conducting evaluations or
                assessments regarding the qualities and characteristics of its Users. It is imperative to
                acknowledge that SportiveBuddy assumes no responsibility for the quality and
                attributes of the Users utilizing the platform. As a result, the Platform absolves itself of
                liability for any damages that may arise from the placement of advertisements or the
                selection of candidates through the Service. The User is advised to exercise due
                diligence and discernment when engaging with others on the platform, as
                SportiveBuddy does not undertake controls or verifications related to the personal
                qualities and attributes of its user base</p>

            <p>5.2 The onus is entirely upon you to make selections, engage in conversations, and
                establish arrangements in accordance with your own preferences and criteria. The
                process of selecting and deciding whether to maintain contact with a specific User or
                to schedule an appointment rests entirely within your control. SportiveBuddy explicitly
                refrains from any involvement in the interactions that transpire between Users in
                connection with the Service, including any resulting appointments or arrangements. </p>

            <p>5.3 It is crucial to emphasize that SportiveBuddy does not intervene in the contact
                established between Users or in the subsequent appointments and arrangements that
                may ensue. If you encounter dissatisfaction or have a complaint concerning a specific
                User, you are encouraged to utilize the reporting and blocking mechanisms available
                through the Platform. This ensures that you can take appropriate actions to address
                concerns or issues that may arise during your interactions within the SportiveBuddy
                community. In the event of dissatisfaction or the occurrence of complaints regarding a
                User, SportiveBuddy is dedicated to taking the necessary actions to address and
                resolve the issue. This commitment is underlined by our commitment to maintaining a
                secure and positive user experience within the platform. Users are encouraged to
                report or block any concerns they may have through the designated mechanisms on
                the platform, empowering SportiveBuddy to initiate appropriate measures, including
                investigations or interventions, as deemed necessary to uphold the integrity and
                functionality of the Service. This proactive approach ensures that SportiveBuddy
                remains responsive to user feedback and can effectively address any challenges or
                concerns that may arise during the course of interactions within the SportiveBuddy
                community.
            </p>

            <p>5.4 You are entirely accountable and legally liable for all your actions conducted with
                the assistance of the Platform and/or Service. This encompasses all decisions,
                interactions, or engagements within the SportiveBuddy platform, and you expressly
                acknowledge that SportiveBuddy disclaims any responsibility or legal liability arising
                from the outcomes of your actions. This acknowledgment emphasizes the need to
                exercise due diligence, discretion, and compliance with the prescribed guidelines while
                utilizing the features and functionalities of the Platform and/or Service.

            </p>

            <p>5.5 The User is prohibited from:
            </p>

            <ul>
                <li>It is strictly prohibited for the User and others to employ any tools other than those
                    explicitly approved by SportiveBuddy to conduct searches on the Platform or
                    access the Database. The User and others are expressly forbidden from engaging
                    in data mining activities, utilizing robots, or employing any software and/or
                    hardware tools and/or solutions, whether independently initiated or provided by
                    third parties. This prohibition extends to activities aimed at extracting information
                    accessible through the Database, including but not limited to spidering, scraping,
                    searching, or any other illegitimate methods of use and/or perusal of the Database.
                    Such unauthorized actions are in direct violation of the Terms and Conditions set
                    forth by SportiveBuddy.</li>
                <li>Collecting information of other Users through the Service and Platform with the
                    intention of utilizing it for purposes beyond those specifically detailed in these
                    Terms and Conditions is expressly forbidden. Any such action requires the
                    emphatic written consent of SportiveBuddy. Unauthorized collection, use, or
                    exploitation of user information for alternative purposes is in direct violation of the
                    terms outlined in these Terms and Conditions and is subject to enforcement
                    measures by SportiveBuddy. It is imperative to adhere to the stipulated guidelines
                    and seek explicit written consent from SportiveBuddy before engaging in any
                    activities involving the use of collected user information for purposes beyond the
                    scope defined in these Terms and Conditions</li>
                <li>Engaging in the replication, public dissemination, sale, commercial utilization, or
                    any form of provision to third parties of the Content obtained through the Service
                    is explicitly prohibited. Such activities are strictly forbidden, and Users are
                    expected to refrain from any unauthorized distribution or commercialization of
                    Content acquired through the Service. Any violation of this prohibition is subject to
                    enforcement measures by SportiveBuddy, in accordance with the Terms and
                    Condition. It is imperative to respect the proprietary nature of the Content and
                    refrain from actions that contravene the specified restrictions on its use and
                    distribution.</li>
                <li>The involvement of third parties to carry out any of the actions enumerated in this
                    article is explicitly forbidden. Users are expressly prohibited from outsourcing or
                    delegating to external entities the performance of activities outlined in this section.
                    Such activities include, but are not limited to, searches on the Platform, data
                    mining, information collection, or any other actions that contravene the specified
                    terms and conditions. Any attempt to involve third parties in such actions is
                    considered a breach of SportiveBuddy's policies, and appropriate measures will
                    be taken in accordance with the terms delineated in the Terms and Conditions. It
                    is imperative for users to personally adhere to the stipulated guidelines and refrain
                    from engaging external parties in activities that infringe upon the established
                    Terms and Conditions</li>
            </ul>

            <p>5.6 By participating in the Service, you explicitly acknowledge and agree that the
                Profiles and/or other Content you choose to make available through the platform may
                be accessed and used by other Users. It is imperative to understand that
                SportiveBuddy does not exert influence or control over the extent to which other Users
                and/or third parties adhere to these Terms and Conditions. Consequently,
                SportiveBuddy cannot guarantee or regulate the actions of other Users or third parties
                with regard to the utilization of the content you provide within the Service. This
                acknowledgment underscores the importance of exercising discretion and ensuring
                that the information shared aligns with your preferences and objectives within the
                SportiveBuddy community.
            </p>


            <h1>6 - Posting Content is strictly prohibited under the
                following circumstances:
            </h1>


            <ul>
                <li>Content that is discriminatory based on appearance, race, religion, gender, culture,
                    background, or is otherwise deemed offensive or inappropriate, as determined at
                    the sole discretion of SportiveBuddy. Such determinations will be made in
                    accordance with the guidelines and standards set forth by SportiveBuddy,
                    emphasizing the commitment to fostering an inclusive and respectful environment
                    within the platform. Users are expected to refrain from posting any content that
                    may be considered discriminatory, offensive, or inappropriate, and SportiveBuddy
                    reserves the right to enforce these prohibitions to maintain a positive and
                    welcoming community atmosphere.
                </li>
                <li>Content that advocates violence against and/or harassment of another person or
                    persons, whether leading to or resulting from the exploitation or abuse of others.
                    Additionally, any Content promoting or facilitating the conduct of illegal activities is
                    expressly prohibited. These prohibitions are in place to ensure the promotion of a
                    safe, respectful, and lawful environment within the SportiveBuddy platform. Users
                    are expected to refrain from posting any content that falls within these categories,
                    and SportiveBuddy reserves the right to enforce these restrictions to maintain the
                    integrity and well-being of its community.</li>
                <li>Content that, according to SportiveBuddy's judgment, breaches standards of
                    decency or good taste, or is of a violent nature. SportiveBuddy holds the authority
                    to determine what constitutes a violation of decency or good taste, or falls within
                    the category of violent content. This restriction is in place to uphold community
                    standards and create an environment that reflects a commitment to decency, good
                    taste, and non-violence. Users are expected to exercise discretion, and
                    SportiveBuddy retains the right to enforce these standards to cultivate a positive
                    and respectful platform atmosphere.
                    • Content that solicits personal information from minors, discloses personal
                    information of other individuals, or includes your contact information. This
                    prohibition is implemented to safeguard the privacy and security of all users within
                    the SportiveBuddy platform. Users are expressly forbidden from creating content
                    that involves the request for personal information from minors, the sharing of
                    personal details about others, or the inclusion of one's own contact information.
                    SportiveBuddy enforces this restriction to uphold the privacy and well-being of the
                    community and to ensure a secure and trustworthy environment for all users.
                </li>
                <li>Content that includes viruses, Trojan horses, worms, bots, or any other software
                    designed to cause harm, render a computerized work unusable or inaccessible,
                    delete or appropriate it, or circumvent the technical security measures of the
                    Website and/or the computer systems of SportiveBuddy. This prohibition is in place
                    to ensure the integrity and security of the SportiveBuddy platform and to prevent
                    any malicious activities that could compromise the functionality or security of the
                    Platform and associated computer systems. Users are expected to refrain from
                    posting any content containing such harmful elements, and SportiveBuddy
                    reserves the right to enforce this prohibition to maintain a safe and secure online
                    environment.
                    • Content that is based on falsehoods and/or is misleading, or involves assuming a
                    false identity and/or falsely suggesting that the User is associated with
                    SportiveBuddy, is strictly prohibited. This prohibition is in place to maintain the
                    authenticity and credibility of the SportiveBuddy platform. Users are expressly
                    forbidden from creating content that disseminates false information, misleads
                    others, or falsely represents their identity in a manner that implies an association
                    with SportiveBuddy. SportiveBuddy enforces this restriction to uphold the
                    trustworthiness of the community and to ensure that users engage in a transparent
                    and honest manner within the platform.</li>

                <li>Engaging in the posting of Content involving chain letters, junk mail, or spamming,
                    or soliciting passwords or other traceable information from individuals for
                    commercial or illegal purposes is strictly prohibited. This prohibition is in place to
                    prevent the proliferation of unwanted or deceptive communications within the
                    SportiveBuddy platform. Users are expressly forbidden from participating in
                    activities such as chain letters, junk mail, spamming, or soliciting sensitive
                    information for illicit or commercial motives. SportiveBuddy enforces this restriction
                    to maintain the integrity of the platform and protect users from unwanted or
                    potentially harmful interactions.</li>

                <li>Content that violates the rights of SportiveBuddy and/or third parties, including but
                    not limited to Intellectual Property Rights or rights related to the protection of
                    privacy, is strictly prohibited. This prohibition is in place to safeguard the rights and
                    interests of both SportiveBuddy and other users within the platform. Users are
                    expressly forbidden from creating content that infringes upon the intellectual
                    property rights or privacy rights of SportiveBuddy or any third parties.
                    SportiveBuddy enforces this restriction to maintain a fair and lawful environment,
                    respecting the rights of all parties involved in the SportiveBuddy community.</li>

                <li>Content that violates these Terms and Conditions, the Privacy Policy, or any
                    applicable legislation and/or regulation, or is otherwise illegitimate in any manner
                    that may impair the interests and reputation of SportiveBuddy, is strictly prohibited.
                    This prohibition is in place to uphold the standards, integrity, and reputation of the
                    SportiveBuddy platform. Users are expressly forbidden from creating content that
                    contravenes the established user guidelines, privacy policies, or legal regulations,
                    as such actions can adversely impact the interests and standing of SportiveBuddy.
                    SportiveBuddy enforces this restriction to ensure compliance with the platform's
                    rules, legal obligations, and ethical standards, fostering a positive and reputable
                    online community.</li>

                <li> SportiveBuddy retains the right to edit, alter, reject, or delete Content from the
                    Platform if deemed necessary in the opinion of SportiveBuddy. It is emphasized that
                    such actions do not confer any entitlement on your part to compensation for damages
                    and/or establish liability on the part of SportiveBuddy. If you believe that specific
                    Content violates your rights or the rights of another User or a third party, it is imperative
                    that you promptly report such instances to SportiveBuddy.
                </li>
            </ul>



            <h1>7 - Paid Services:</h1>

            <p>7.1 Presently, SportiveBuddy does not provide any paid services. Nevertheless, it is
                anticipated that there may be the introduction of paid services in the future. In the event
                of such a development, comprehensive details will be communicated through
                announcements and will be explicitly incorporated into the updated Terms and
                Conditions. SportiveBuddy is committed to transparency, and your permission will be
                actively sought for acceptance of these revised terms related to any forthcoming paid
                services. It is advisable to stay informed and review the updated Terms and Conditions
                to ensure clarity and understanding regarding any changes to the service offerings.
            </p>



            <h1>8 - Intellectual Property Rights</h1>

            <p>8.1 The Intellectual Property Rights pertaining to the Service, encompassing, but not
                limited to, the Platform and the Database, along with the information disseminated
                through the Platform and Service—comprising texts, visual aesthetics, Profile
                templates, video, audio, and visual or photographic materials, excluding the Content—
                are the sole property of SportiveBuddy and/or its licensors.</p>

            <p>8.2 In accordance with the terms and conditions outlined herein, SportiveBuddy grants
                you a limited, personal, revocable, non-exclusive, non-sub-licensable, and nontransferable right to access and utilize the Service. This encompassing right extends
                to the Database, the Content, and the Platform and is specifically designated for the
                purposes described within these Terms and Conditions. It is important to note that this
                right is subject to adherence to the specified conditions, and SportiveBuddy reserves
                the authority to revoke or modify this right as deemed necessary. This grant of access
                and usage is solely for your personal use and is not transferable or sublicensable to
                any third party.
            </p>

            <p>8.3 As a general rule, you retain the Intellectual Property Rights related to the Content
                you post. However, it's essential to acknowledge and agree that by making Content
                available or uploading it, you automatically grant SportiveBuddy a free, worldwide,
                irrevocable, sub-licensable, and transferable license. This license empowers
                SportiveBuddy to publicly display, reproduce, and incorporate the Content into the
                Database. This grant is made within the context of providing and enhancing the
                Service. It's important to recognize that this license does not diminish your ownership
                of Intellectual Property Rights but is necessary for SportiveBuddy to facilitate the
                functionality and features of the Service.</p>

            <p>8.4 By uploading or making Content available, you affirmatively guarantee to
                SportiveBuddy that you are the rightful and full rights holder concerning the said
                Content. Furthermore, you assert that you possess the complete entitlement and
                authority necessary to grant the license specified in this article to SportiveBuddy. This
                guarantee is essential in confirming that your contribution of Content to the Service is
                in compliance with intellectual property laws and regulations, and that SportiveBuddy
                can exercise the granted license without infringement on any third-party rights.
            </p>

            <p>8.5 It is expressly prohibited to download, copy, modify, reverse engineer, publicly
                disclose, or utilize, for purposes other than those explicitly specified in these Terms
                and Conditions, any information made accessible through the Service or the Website.
                This prohibition stands unless SportiveBuddy or the pertinent rights holder has
                provided explicit consent or unless such use is mandated by Estonian legislation.</p>


            <h1>9 - Privacy</h1>

            <p>9.1 In the process of creating your Profile and engaging with the Service, you are
                required to provide (personal) data to SportiveBuddy. It is crucial to note that the
                processing of this (personal) data is conducted in strict accordance with
                SportiveBuddy's Privacy Policy and in compliance with the relevant legislation and
                regulations governing data protection and privacy. This commitment underscores
                SportiveBuddy's dedication to ensuring the confidentiality, security, and lawful
                processing of any information you share during your interaction with the platform. For
                a comprehensive understanding of how your data is handled, it is advisable to refer to
                SportiveBuddy's Privacy Policy, which outlines the specific practices and measures in
                place to safeguard your privacy rights.</p>




            <h1>10 - Assurances and Protections</h1>

            <p>10.1 You expect liability towards SportiveBuddy and undertake to fully indemnify
                SportiveBuddy against any damages and costs arising from a failure on your part to
                comply with the terms of the Agreement, any actions you take while utilizing the
                Service, or engagement in any unauthorized or unlawful activities. This commitment
                includes the responsibility to compensate SportiveBuddy for all costs incurred and
                damages suffered that are in any manner associated with the aforementioned claims.
                By accepting this obligation, you acknowledge the importance of mitigating any
                adverse consequences SportiveBuddy may face due to your actions or any breaches
                of the Agreement, thereby ensuring a compensation by you</p>

            <p>10.2 You provide a guarantee to SportiveBuddy that the information supplied during
                the creation of your Profile and the posting of your Content is accurate, up-to-date, and
                complete. You acknowledge and comprehend the critical significance of the accuracy,
                timeliness, and completeness of the provided Content for the optimal functioning of the
                Service.</p>

            <p>10.3 You offer an unequivocal guarantee to SportiveBuddy, affirming your entitlement
                to utilize the Service and your commitment to adhere to these Terms and Conditions.
                Additionally, you undertake the responsibility to indemnify SportiveBuddy against any
                third-party claims that may arise, contending that your utilization of the Service,
                including but not limited to the posting of Content, is conducted in an illegitimate
                manner. This guarantee serves to underscore your commitment to lawful and
                responsible use of the Service, while also providing SportiveBuddy with protection
                against potential legal claims arising from your actions within the Platform.</p>


            <h1>11 - Liability</h1>

            <p>11.1 SportiveBuddy holds no liability for damages resulting from the provision of the
                Service, illegitimate actions, or any other causes, to the extent permissible under
                mandatory law. This disclaimer underscores the acknowledgment that certain legal
                provisions may limit the extent to which liability can be assumed in specific
                circumstances.</p>

            <p>11.2 SportiveBuddy is not liable for any consequential damages, including but not
                limited to pure financial losses, loss of turnover and profit, loss of data, and immaterial
                damages, related to or resulting from the utilization of the Service.
            </p>

            <p>11.3 The limitation to liability specified in this article does not come into effect in
                instances of SportiveBuddy's intentional wrongdoing or deliberate recklessness,
                including such actions by its management. This exception ensures that, in cases of
                deliberate and egregious conduct on the part of SportiveBuddy or its management, the
                limitation to liability does not apply, and full accountability is maintained.</p>


            <p>11.4 A crucial condition for any entitlement to compensation for damage is the prompt
                reporting of the damage in writing to SportiveBuddy immediately after its occurrence.
                Additionally, it is noteworthy that any claim for compensation of damage against
                SportiveBuddy automatically lapses with the mere passage of 9 (nine) months from
                the point of the claim's origination. This stipulation emphasizes the importance of timely
                notification and establishes a time frame within which claims must be asserted,
                contributing to the efficiency and procedural clarity in addressing potential damages.</p>












            <h1>12 - Reporting about Unauthorized or False
                Information
            </h1>

            <p>12.1 SportiveBuddy explicitly disclaims liability for any damages associated with the
                (illegitimate) use of the Platform. However, SportiveBuddy does acknowledge a
                commitment under the conditions outlined below. Upon receipt of a report,
                SportiveBuddy is obliged to take immediate action, which may involve the removal of
                unmistakably illegitimate material or the cessation of activities that are deemed
                indisputably illegitimate. This provision is designed to address instances of clear
                wrongdoing reported by users, ensuring a responsive approach to maintaining the
                integrity and legitimacy of the platform.
            </p>

            <p>12.2 SportiveBuddy retains the right to withhold approval for a request to block material
                or terminate an activity if there are legitimate reasons to doubt the accuracy of the
                report or the legitimacy of the accompanying evidence, or if a careful consideration of
                interests necessitates such a decision. In such instances, SportiveBuddy may, for
                example, request a court ruling from a competent court in Estonia. This ruling should
                substantiate that the identified material or activity is unequivocally illegitimate. This
                approach ensures a thorough and legally sound evaluation before any decisive actions
                are taken.
            </p>

            <p>12.3 SportiveBuddy is under no obligation to become a party or involve itself in any
                manner in a dispute between the individual reporting an issue and any third party. This
                position underscores SportiveBuddy's stance of non-involvement in disputes,
                emphasizing that resolution and proceedings between the reporting party and external
                entities fall outside the purview of SportiveBuddy's responsibilities or engagement.</p>


            <p>12.4 The individual reporting assumes the responsibility of indemnifying SportiveBuddy
                against any claims by third parties related to the blocking or removal of material or the
                termination of activities. This indemnification extends to all damages and costs
                incurred or that SportiveBuddy may still incur in connection with such a claim. This
                includes, but is not limited to, the reimbursement of legal assistance costs. This
                safeguard underscores the individual reporting's commitment to absolve
                SportiveBuddy from any potential liabilities arising from the reported actions.</p>







            <h1>13 - Period of Effectiveness and Termination
            </h1>

            <p>13.1 You maintain the prerogative to suspend your engagement with the Service at
                your own discretion, exercising the right to temporarily halt its utilization whenever you
                deem fit. Additionally, you are empowered to permanently remove your Profile from
                the Platform whenever you wish to conclude your participation in the Service. This
                autonomy allows you the flexibility to manage and control your presence on the
                platform in alignment with your preferences and needs.
            </p>

            <p>13.2 Upon the conclusion of the agreement, regardless of the reason, your entitlement
                to utilize the Service is promptly terminated, resulting in immediate denial of access to
                the platform. Simultaneously, SportiveBuddy promptly removes your Profile from the
                platform upon termination for any cause. SportiveBuddy, as outlined in Intellectual
                Property Rights sections (see above), retains the right to utilize all Content. However,
                post-termination, SportiveBuddy commits to removing or anonymizing all Content upon
                your initial request. It is important to note that SportiveBuddy is not obligated to furnish
                or convert any Content for you following the termination of the agreement.

            </p>





            <h1>14 - Miscellaneous
            </h1>

            <p>14.1 Estonian legislation is applicable to these Terms and Conditions and governs all
                aspects of the use of the Service and the Platform
            </p>

            <p>14.2 All disputes that may arise between you and SportiveBuddy will be subjected to
                resolution by the competent court in the district of Tallinn, unless there are mandatory
                legal provisions directing that the dispute be brought before a different court. This
                agreement on jurisdiction underscores the parties' commitment to resolving disputes
                within a defined legal framework and ensures clarity on the venue for any potential
                legal proceedings.
            </p>

            <p>14.3 SportiveBuddy retains the right to transfer the rights and obligations arising from
                these Terms and Conditions to third parties and will provide you with appropriate
                notification of such transfer. In the event that you find the transfer of obligations to a
                third party unacceptable, you have the option to discontinue your use of the Service
                and terminate your Profile. This provision ensures transparency and grants you the
                autonomy to make an informed decision regarding your continued engagement with
                the platform.
            </p>




            <p>14.4 In the event that any part of these Terms and Conditions is deemed or becomes
                partially invalid, both you and SportiveBuddy shall continue to be bound by the
                remaining valid provisions. SportiveBuddy is obligated to replace the invalid portion
                with provisions that are valid, and the legal consequences of these substitute
                provisions, considering the essence and context of these Terms and Conditions, shall
                align as closely as possible with those of the invalid section. This provision is designed
                to ensure the ongoing applicability and coherence of the agreement, even if specific
                sections are invalidated.
            </p>

        </div>

    );
};

export default Terms;
